[package]
name = "sn_httpd"
version = "0.1.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.5"
actix-http = "3"
actix-rt = "2.7"
actix-service = "2"
actix-web = "4"
anyhow = "1.0.80"
log = "0.4.21"
env_logger = "0.11.3"
serde = "1.0.197"
serde_json = "1.0.114"
dirs-next = "2.0.0"
tokio = { version = "1.36.0", features = ["rt", "macros"] }
sn_client = "=0.105.3"
sn_node = "=0.105.6"
sn_peers_acquisition = "=0.2.10"
sn_transfers = "=0.17.2"
xor_name = "5.0.0"
chrono = "0.4.35"
regex = "1.10.3"
hex = "0.4.3"
color-eyre = "~0.6"
clap = { version = "4.5.2", features = ["derive"] }
multiaddr = "0.18.1"
async-stream = "0.3.5"
tempfile = "3.10.1"
bytes = "1.5.0"
futures = "0.3.30"